# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - actual-budget

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Yarn install
        run: yarn install

      - name: Check and run build script
        run: |
          if yarn run build --if-present; then
            echo "Build script executed successfully"
          else
            echo "No build script found, skipping..."
          fi

      - name: Check and run test script
        run: |
          if yarn run test --if-present; then
            echo "Test script executed successfully"
          else
            echo "No test script found, skipping..."
          fi

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7067F3016A684024BFD34571CE427C5B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D87FB7CD0A94D8094D77F18A5C0B07A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8BC56B4525944BCEAC9D38696FAE911A }}

      - name: Add delay before deployment
        run: sleep 30

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'actual-budget'
          slot-name: 'Production'
          package: .
